[package]
name = "json-hydrate-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "json_hydrate"
crate-type = ["cdylib"]

[dependencies]
json-hydrate = { version = "0.1", path = "../json-hydrate" }
pyo3 = "0.18"
pythonize = "0.18"
serde_json = "1"
